[package]
edition = "2021"
name = "transactions_and_requests_integrity"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "transactions_and_requests_integrity"

[dependencies]
hdi = { workspace = true }
serde = { workspace = true }
bridge_hc_types = { workspace = true }